# Generated by Django 3.2 on 2023-04-25 14:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_auto_20230420_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='cat',
            name='changed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cat',
            name='deleted',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='is_purebred',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FavouriteToyCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.cat')),
                ('toy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.toy')),
            ],
        ),
        migrations.AddField(
            model_name='cat',
            name='toys',
            field=models.ManyToManyField(through='cats.FavouriteToyCat', to='cats.Toy'),
        ),
    ]
